// Word bank (Thai + English mix)
// แก้ไข / เพิ่ม / ลบคำได้ที่นี่ — ระบบจะสุ่ม 25 คำต่อเกมจาก array นี้
export const WORDS = [
  // General Objects
  "ARM","BAND","BANK","BAR","BELL","BLOCK","BOARD","BOLT",
  "BOMB","BOOT","BOTTLE","BOW","BOX","BRIDGE","BRUSH","BUTTON",
  "CAP","CARD","CELL","CHAIN","CHEST","CLUB","CODE","COLUMN",
  "COMIC","COMPOUND","CONTRACT","CORD","COTTON","CRANE","CYCLE",
  "DECK","DEVICE","DIAMOND","DRAFT","DRILL","DROP","ENGINE",
  "FILE","FILM","FORK","FRAME","GEAR","GLASS","GLOVE","HAMMER",
  "HOOK","HORN","JET","JUNK","KEY","KID","KNIFE","KNOT",
  "LAB","LASER","LEAD","LETTER","LINE","LINK","LOCK","LOG",
  "MACHINE","MAIL","MAP","MATCH","MINE","MODEL","MOLE","NAIL",
  "NET","NOTE","NUT","OIL","PACKAGE","PALM","PAPER","PEN",
  "PIPE","PISTOL","PLANE","PLASTIC","PLATE","PLOT","POCKET",
  "PORT","POST","PRESS","PUMP","RACKET","RAY","RECORD","RING",
  "ROBOT","ROPE","ROW","RULER","SATELLITE","SCALE","SCREEN",
  "SCROLL","SEAL","SERVER","SHAFT","SHIP","SHOT","SIGN","SINK",
  "SKULL","SLIP","SPRING","STAMP","STICK","STOCK","STREAM",
  "STRING","SUIT","SWITCH","TABLE","TAG","TAP","TICKET","TOOL",
  "TORCH","TOWER","TRACK","TRAIN","TRUNK","TUBE","VACUUM",
  "VAN","WALL","WATCH","WHEEL","WIRE",

  // Places
  "AIRPORT","ARENA","BASE","BEACH","CAMP","CASTLE","CAVE",
  "CHURCH","COURT","DESERT","FACTORY","FIELD","FOREST","FORT",
  "GARDEN","HARBOR","HOSPITAL","HOTEL","ISLAND","JAIL",
  "LIBRARY","MARKET","MUSEUM","OFFICE","PARK","PRISON",
  "PYRAMID","SCHOOL","SHOP","STADIUM","STATION","TEMPLE","THEATER",
  "TUNNEL","UNIVERSITY","WAREHOUSE","YARD",

  // Nature
  "AIR","ASH","CLOUD","COAST","COMET","DUST","FIRE","FLOWER",
  "FOG","GLACIER","GRASS","HILL","ICE","LAKE","LEAF",
  "LIGHT","LIGHTNING","MOUNTAIN","MUD","OCEAN","RAIN","RAINBOW",
  "RIVER","ROCK","ROOT","SAND","SEA","SEED","SHADOW","SKY",
  "SMOKE","SNOW","SPACE","STAR","STORM","SUN","SWAMP","THUNDER",
  "TREE","VALLEY","VOLCANO","WATER","WAVE","WIND",

  // Animals
  "ANT","BAT","BEAR","BEETLE","BIRD","BULL","CAMEL","CAT",
  "COBRA","CRAB","CROW","DEER","DOG","DRAGON","DUCK","EAGLE",
  "FALCON","FOX","GOAT","HAWK","HORSE","LION","LOBSTER","MAMMOTH",
  "MONKEY","MOUSE","OWL","PANTHER","PIG","RABBIT","RAT","RHINO",
  "SCORPION","SHARK","SNAKE","SPIDER","SQUID","TIGER",
  "TURTLE","VIPER","WHALE","WOLF",

  // People & Roles
  "ACTOR","AGENT","ARTIST","CAPTAIN","CHEF","DOCTOR","DRIVER",
  "ENGINEER","FARMER","GIANT","GUARD","HUNTER","JUDGE","KING",
  "KNIGHT","LAWYER","LEADER","MAGICIAN","NINJA","NURSE","PILOT",
  "PIRATE","POLICE","PRIEST","PRINCE","PRISONER","QUEEN",
  "SAILOR","SCIENTIST","SOLDIER","SPY","STUDENT","TEACHER","THIEF",
  "WAITER","WARRIOR","WITNESS","WIZARD",

  // Food & Drink
  "APPLE","BREAD","BUTTER","CAKE","CANDY","CHEESE","CHERRY",
  "CHOCOLATE","COFFEE","COOKIE","CREAM","EGG","FISH","GRAPE",
  "HONEY","JUICE","LEMON","MEAT","MILK","MINT","NOODLE",
  "OLIVE","ONION","ORANGE","PEACH","PEAR","PEPPER",
  "PIZZA","POTATO","RICE","SALAD","SALT","SOUP","STEAK","SUGAR",
  "TEA","TOMATO","WATER","WINE",

  // Abstract / Ambiguous
  "ACTION","ATTACK","BALANCE","BATTLE","BLAST","BREAK","CASE",
  "CHARGE","CHECK","CIRCLE","CLASH","COMMAND","CONTROL","CRASH",
  "CRIME","CROSS","CROWN","DANGER","DASH","DEAL","DEATH",
  "DEFENSE","DESIRE","DESTINY","DOUBLE","DREAM","ECHO","ENERGY",
  "ESCAPE","EXCHANGE","FALL","FATE","FEAR","FLIGHT","FORCE",
  "FREEDOM","GAME","GLORY","GRAVITY","GROUND","GUESS","HEART",
  "HIDE","HONOR","HOPE","HUNT","IDEA","IMPACT","JOKE","JOURNEY",
  "JUMP","JUSTICE","KISS","KNOWLEDGE","LIFE","LIMIT",
  "LUCK","MAGIC","MARK","MEMORY","MESSAGE","MISSION","MIST",
  "MOTION","MYSTERY","ORDER","PAIN","PEACE","PLAN","POWER",
  "RACE","RISK","RULE","RUSH","SCORE","SECRET","SHOCK","SIGNAL",
  "SILENCE","SKILL","SLEEP","SOUND","SPEED","SPIRIT","SPOT",
  "STRIKE","STYLE","TARGET","TEMPTATION","TIME","TOUCH","TRAP",
  "TRUTH","VICTORY","VISION","VOICE","WAR","WARNING","WISH",

  // Classic Weirdness
  "ALIEN","ANGEL","ATLANTIS","CASINO","CENTAUR","CYCLOPS",
  "EMBASSY","GENIUS","GHOST","HOLLYWOOD","MERCURY","MOON",
  "NOVA","OLYMPUS","ORACLE","PHOENIX","RAVEN",
  "SATURN","SPHINX","TEMPEST","UNICORN","VENUS","ZEUS"
];
